Add support for $search
AutoMapper/AutoMapper.Extensions.OData pull request #119
Opened 2022-02-05 14:28 UTC by trojanmartin

Implements support for $search clause from odata query options which was discussed here #118.  

Brief explanation: 
 If user defines search binder, map his expression and use it in filter. If $search and $filter are defined at the same time, both filters must be applied.

2022-02-06 17:48 UTC, BlaiseD commented
@trojanmartin can you add the new tests to  both `GetQueryTests` files?  ([here](https://github.com/trojanmartin/AutoMapper.Extensions.OData/blob/feat/seach-query-option/AutoMapper.OData.EF6.Tests/GetQueryTests.cs) and [here](
https://github.com/trojanmartin/AutoMapper.Extensions.OData/blob/feat/seach-query-option/AutoMapper.OData.EFCore.Tests/GetQueryTests.cs)).

You'll probably need to update the [Initialize](https://github.com/trojanmartin/AutoMapper.Extensions.OData/blob/eaea47612fb4a3debc3851c5a1dc2be8beb5d6c6/AutoMapper.OData.EF6.Tests/GetQueryTests.cs#L39) methods and  possibly some of the setup code [here](https://github.com/trojanmartin/AutoMapper.Extensions.OData/blob/eaea47612fb4a3debc3851c5a1dc2be8beb5d6c6/AutoMapper.OData.EF6.Tests/GetTests.cs#L531) and [here](https://github.com/trojanmartin/AutoMapper.Extensions.OData/blob/eaea47612fb4a3debc3851c5a1dc2be8beb5d6c6/AutoMapper.OData.EFCore.Tests/GetTests.cs#L596).

2022-02-06 17:49 UTC, BlaiseD reviewed
Please add tests (similar to the new web tests) to both `GetQueryTests` files.  Looks good otherwise.

2022-02-08 13:56 UTC, BlaiseD requested changes
I should have hit the **Request Changes** radio button here to be clear.

Please add tests (similar to the new web tests) to both `GetQueryTests` files. Looks good otherwise.

2022-02-09 21:38 UTC, trojanmartin commented
@BlaiseD tests added

2022-02-10 11:38 UTC, BlaiseD approved these changes

2022-02-10 11:54 UTC, merged