Adds support for $skip and $top with no order specified
AutoMapper/AutoMapper.Extensions.OData pull request #123
Opened 2022-02-18 03:09 UTC by wbuck

Implements support for `$skip` and `$top` when a order is not explicitly specified which was discussed here #94.

Description:
When either `$skip`, `$top`, or both are specified without an explicit `$orderby` a default order is now created using a suitable property on the model.

2022-02-19 14:54 UTC, BlaiseD requested changes
I think we need to handle composite keys i.e. when `KeyAttribute` has been applied to multiple fields (not sure if it throws when an Id has also been applied - both convention and configuration are being used) [e.g. here](https://github.com/OData/WebApi/blob/ba2929203aba732b5a019adf717e189bc1240a1f/src/Microsoft.AspNet.OData.Shared/Query/ODataQueryOptions.cs#L691) multiple fields are being returned.

It's ok to create some data structure until `ThenBy` is null and build an expression from that.
```c#
public class OrderBySetting
{
	public string Name { get; set; }
	public OrderBySetting ThenBy { get; set; }
}
```

Agree?

2022-02-19 17:26 UTC, wbuck commented
Yeah that's right, completely forgot about composite keys. When using the fluent API I'm unsure how I can determine if an entity is using a composite key.

In order to do that I think I'll need to pass a reference to the `ODataQueryContext` (I believe I have access to the model and container through the context).

2022-02-19 19:55 UTC, BlaiseD commented
I would have thought the following would work:
```c#
    public class SomeEntity
    {
        [Key]
        public int Identity1 { get; set; }
        [Key]
        public int Identity2 { get; set; }
        public string Name { get; set; }
    }
```

Then [this](https://github.com/wbuck/AutoMapper.Extensions.OData/blob/80f6e1a780cee9e502cc7e3ef67249c61c3debe6/AutoMapper.AspNetCore.OData.EFCore/TypeExtensions.cs#L21) becomes a `Where()`.

Everything including the ID properties goes to a hash set.

On second thoughts, maybe it's possible to just grab the keys from the context.

![image](https://user-images.githubusercontent.com/7595209/154816660-c4bfbb86-1632-4cf4-abcf-85ca6e95d7eb.png)

Either way works.  If the "how to retrieve the composite keys" piece is wrong then it can be resolved in a separate PR.

Thanks.

2022-02-19 21:01 UTC, wbuck commented
Yeah, they're using the context in order to attain the keys for a type as well. 
I think the problem with the context approach is when we're dealing with child collections.

I'll explore a bit more see what I can come up with.

2022-02-20 13:54 UTC, wbuck commented
So I have a tentative implementation using the `ODataQueryContext` to find the entities/keys I need.
Interested in your thoughts on this approach thus far.

I need to create more tests/test data to get some coverage for entities with multiple keys.

2022-02-21 02:56 UTC, wbuck commented
OK, so it's looking good now in terms of ordering by a single, or multiple keys.
As a result the code has been simplified which is always a plus.

2022-02-21 17:43 UTC, BlaiseD approved these changes

2022-02-21 18:03 UTC, merged

2022-02-21 20:07 UTC, BlaiseD commented
Thanks @wbuck